// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFolder(arg1) {
  return window['go']['backend']['App']['OpenFolder'](arg1);
}

export function OpenInputFilePicker() {
  return window['go']['backend']['App']['OpenInputFilePicker']();
}

export function OpenInputFolderPicker() {
  return window['go']['backend']['App']['OpenInputFolderPicker']();
}

export function OpenSaveLocationPicker() {
  return window['go']['backend']['App']['OpenSaveLocationPicker']();
}

export function RunConversion(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['RunConversion'](arg1, arg2, arg3, arg4);
}
