// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunConversion(arg1:Array<string>,arg2:boolean,arg3:string,arg4:string):Promise<void>;
